name: custom_serializer
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_value: ^6.3.0
  built_collection: ^4.1.0


  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: ^1.2.3
  built_value_generator: ^6.3.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
